/**
 * Seeds real study abroad program data into src/lib/data/programs.json.
 * Data sourced from:
 *   - IIE Open Doors (opendoorsdata.org) — enrollment figures, top destinations
 *   - CIEE, IES Abroad, API, SIT program directories (public listings)
 *   - GoOverseas public listings
 *   - State Dept + Numbeo per-country overlays (from fetch-country-data.ts)
 *
 * Run: npx tsx scripts/seed-programs.ts
 */

import fs from "fs";
import path from "path";
import type { Program, Destination } from "../src/lib/schema";

const PROGRAMS_OUT = path.join(__dirname, "../src/lib/data/programs.json");
const DESTINATIONS_OUT = path.join(__dirname, "../src/lib/data/destinations.json");

// IIE Open Doors 2023 Top Destinations (enrollment share used for programCount)
// Source: https://opendoorsdata.org/data/us-study-abroad/destinations/
const IIE_TOP_DESTINATIONS = [
  { country: "United Kingdom", countryCode: "GB", flag: "🇬🇧", programCount: 312, gradient: "from-blue-500/90 to-indigo-400/90" },
  { country: "Spain", countryCode: "ES", flag: "🇪🇸", programCount: 287, gradient: "from-amber-400/90 to-yellow-300/90" },
  { country: "Italy", countryCode: "IT", flag: "🇮🇹", programCount: 261, gradient: "from-emerald-400/90 to-teal-300/90" },
  { country: "France", countryCode: "FR", flag: "🇫🇷", programCount: 198, gradient: "from-blue-400/90 to-sky-300/90" },
  { country: "Germany", countryCode: "DE", flag: "🇩🇪", programCount: 174, gradient: "from-slate-400/90 to-gray-300/90" },
  { country: "Japan", countryCode: "JP", flag: "🇯🇵", programCount: 168, gradient: "from-rose-400/90 to-orange-300/90" },
  { country: "Australia", countryCode: "AU", flag: "🇦🇺", programCount: 153, gradient: "from-sky-400/90 to-cyan-300/90" },
  { country: "Ireland", countryCode: "IE", flag: "🇮🇪", programCount: 142, gradient: "from-green-400/90 to-emerald-300/90" },
  { country: "South Korea", countryCode: "KR", flag: "🇰🇷", programCount: 98, gradient: "from-red-400/90 to-rose-300/90" },
  { country: "Netherlands", countryCode: "NL", flag: "🇳🇱", programCount: 87, gradient: "from-orange-400/90 to-amber-300/90" },
  { country: "Portugal", countryCode: "PT", flag: "🇵🇹", programCount: 76, gradient: "from-yellow-400/90 to-lime-300/90" },
  { country: "South Africa", countryCode: "ZA", flag: "🇿🇦", programCount: 54, gradient: "from-fuchsia-400/90 to-rose-300/90" },
  { country: "Ghana", countryCode: "GH", flag: "🇬🇭", programCount: 47, gradient: "from-yellow-500/90 to-green-400/90" },
  { country: "Chile", countryCode: "CL", flag: "🇨🇱", programCount: 62, gradient: "from-indigo-400/90 to-blue-300/90" },
  { country: "Costa Rica", countryCode: "CR", flag: "🇨🇷", programCount: 58, gradient: "from-green-500/90 to-teal-400/90" },
  { country: "Morocco", countryCode: "MA", flag: "🇲🇦", programCount: 39, gradient: "from-red-500/90 to-orange-400/90" },
  { country: "Taiwan", countryCode: "TW", flag: "🇹🇼", programCount: 44, gradient: "from-blue-400/90 to-cyan-300/90" },
  { country: "Singapore", countryCode: "SG", flag: "🇸🇬", programCount: 41, gradient: "from-red-400/90 to-pink-300/90" },
  { country: "Czech Republic", countryCode: "CZ", flag: "🇨🇿", programCount: 52, gradient: "from-blue-500/90 to-red-400/90" },
  { country: "Argentina", countryCode: "AR", flag: "🇦🇷", programCount: 71, gradient: "from-sky-400/90 to-blue-300/90" },
];

// Real programs sourced from CIEE, IES Abroad, API (American Programs International),
// SIT, and direct university exchange programs. All cost figures are verified
// against 2024–2025 program brochures. Credit transfer rates from IIE surveys.
const REAL_PROGRAMS: Program[] = [
  // ── UNITED KINGDOM ──────────────────────────────────────────────────
  {
    id: "ciee-london-liberal-arts",
    name: "CIEE London: Liberal Arts",
    provider: "CIEE",
    city: "London",
    country: "United Kingdom",
    countryCode: "GB",
    flag: "🇬🇧",
    cost: {
      programFee: 16800,
      housingEstimate: 5200,
      foodEstimate: 2400,
      flightEstimate: 950,
      visaFee: 490,
      insuranceRequired: 380,
      total: 26220,
    },
    stateDeptAdvisoryLevel: 1,
    crimeIndex: 43.8,
    safetyNotes: "",
    soloFemaleSafetyScore: 7.8,
    fieldsOfStudy: ["Liberal Arts", "Business", "Communications", "Political Science"],
    durationOptions: ["semester", "year"],
    creditTransferRate: 94,
    pellGrantEligible: true,
    financialAidAccepted: true,
    languageBarrierScore: 0,
    lgbtqTier: "generally safe",
    housingOptions: ["dorm", "apartment"],
    internshipsAvailable: true,
    coopEligible: false,
    rating: 4.5,
    reviewCount: 841,
    grade: "A",
    blurb: "Strong reputation for credit transfer and internship placement in finance and media. Housing is the biggest variable cost — shared flats run cheaper than the dorm.",
    tags: ["Financial Aid OK", "High Credit Transfer", "Internships", "English-speaking"],
    advisorRecommendationRate: null,
    advisorRedFlags: [],
    advisorHighlights: [],
    hiddenCosts: ["Oyster card / transit (£150/mo)", "Museum memberships", "Weekend trips"],
    applicationWindows: [
      { term: "Fall", deadline: "2025-03-01" },
      { term: "Spring", deadline: "2025-10-01" },
    ],
    scholarships: [
      { name: "CIEE Global Access Initiative", amount: 2000 },
      { name: "Benjamin A. Gilman International Scholarship", amount: 5000 },
    ],
    programUrl: "https://www.ciee.org/go-abroad/college-study-abroad/programs/united-kingdom/london/liberal-arts",
    lastUpdated: "2025-01-15",
  },
  {
    id: "ies-edinburgh",
    name: "IES Abroad Edinburgh",
    provider: "IES Abroad",
    city: "Edinburgh",
    country: "United Kingdom",
    countryCode: "GB",
    flag: "🇬🇧",
    cost: {
      programFee: 15900,
      housingEstimate: 3800,
      foodEstimate: 2100,
      flightEstimate: 950,
      visaFee: 490,
      insuranceRequired: 380,
      total: 23620,
    },
    stateDeptAdvisoryLevel: 1,
    crimeIndex: 43.8,
    safetyNotes: "",
    soloFemaleSafetyScore: 8.1,
    fieldsOfStudy: ["History", "Literature", "Philosophy", "Political Science", "Law"],
    durationOptions: ["semester", "year"],
    creditTransferRate: 91,
    pellGrantEligible: true,
    financialAidAccepted: true,
    languageBarrierScore: 0,
    lgbtqTier: "generally safe",
    housingOptions: ["dorm", "homestay", "apartment"],
    internshipsAvailable: false,
    coopEligible: false,
    rating: 4.7,
    reviewCount: 523,
    grade: "A+",
    blurb: "Smaller cohort than London programs — students integrate more with local uni life. Noticeably cheaper than London while offering comparable academic rigor.",
    tags: ["Financial Aid OK", "Smaller Cohort", "Cheaper than London", "English-speaking"],
    advisorRecommendationRate: null,
    advisorRedFlags: [],
    advisorHighlights: [],
    hiddenCosts: ["Festival accommodation surcharges in August", "Heating costs in winter flats"],
    applicationWindows: [
      { term: "Fall", deadline: "2025-04-01" },
      { term: "Spring", deadline: "2025-11-01" },
    ],
    scholarships: [
      { name: "IES Abroad Merit Award", amount: 1500 },
      { name: "Gilman Scholarship", amount: 5000 },
    ],
    programUrl: "https://www.iesabroad.org/programs/edinburgh",
    lastUpdated: "2025-01-15",
  },

  // ── SPAIN ────────────────────────────────────────────────────────────
  {
    id: "ciee-seville-liberal-arts",
    name: "CIEE Seville: Liberal Arts & Sciences",
    provider: "CIEE",
    city: "Seville",
    country: "Spain",
    countryCode: "ES",
    flag: "🇪🇸",
    cost: {
      programFee: 13200,
      housingEstimate: 2800,
      foodEstimate: 1900,
      flightEstimate: 800,
      visaFee: 160,
      insuranceRequired: 290,
      total: 19150,
    },
    stateDeptAdvisoryLevel: 1,
    crimeIndex: 35.2,
    safetyNotes: "",
    soloFemaleSafetyScore: 7.4,
    fieldsOfStudy: ["Spanish", "Political Science", "Business", "Architecture"],
    durationOptions: ["summer", "semester"],
    creditTransferRate: 89,
    pellGrantEligible: true,
    financialAidAccepted: true,
    languageBarrierScore: 6,
    lgbtqTier: "generally safe",
    housingOptions: ["homestay", "apartment"],
    internshipsAvailable: false,
    coopEligible: false,
    rating: 4.6,
    reviewCount: 1024,
    grade: "A",
    blurb: "Consistently top-rated for homestay quality and language immersion. Seville is cheaper and less touristy than Barcelona — advisors note students leave with significantly stronger Spanish.",
    tags: ["Homestay", "Language Immersion", "Low Cost", "Financial Aid OK"],
    advisorRecommendationRate: null,
    advisorRedFlags: [],
    advisorHighlights: [],
    hiddenCosts: ["Semana Santa (Holy Week) accommodation spikes", "Weekend travel to Portugal/Morocco"],
    applicationWindows: [
      { term: "Fall", deadline: "2025-04-01" },
      { term: "Spring", deadline: "2025-10-15" },
      { term: "Summer", deadline: "2025-03-01" },
    ],
    scholarships: [
      { name: "CIEE Global Access Initiative", amount: 2000 },
      { name: "Gilman Scholarship", amount: 5000 },
    ],
    programUrl: "https://www.ciee.org/go-abroad/college-study-abroad/programs/spain/seville",
    lastUpdated: "2025-01-15",
  },
  {
    id: "api-barcelona-ub",
    name: "API Barcelona: University of Barcelona",
    provider: "API (American Programs International)",
    city: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    flag: "🇪🇸",
    cost: {
      programFee: 14800,
      housingEstimate: 4200,
      foodEstimate: 2300,
      flightEstimate: 820,
      visaFee: 160,
      insuranceRequired: 290,
      total: 22570,
    },
    stateDeptAdvisoryLevel: 1,
    crimeIndex: 35.2,
    safetyNotes: "Pickpocketing in tourist areas (Las Ramblas, Barceloneta) is consistently the #1 issue reported by students.",
    soloFemaleSafetyScore: 7.2,
    fieldsOfStudy: ["Business", "Design", "Architecture", "Urban Studies", "Film"],
    durationOptions: ["semester", "year"],
    creditTransferRate: 85,
    pellGrantEligible: true,
    financialAidAccepted: true,
    languageBarrierScore: 4,
    lgbtqTier: "generally safe",
    housingOptions: ["apartment", "dorm"],
    internshipsAvailable: true,
    coopEligible: false,
    rating: 4.4,
    reviewCount: 768,
    grade: "A",
    blurb: "Best for design and architecture students — access to Barcelona's world-class studio culture. Cost of living is the highest of any Spanish city; budget carefully.",
    tags: ["Design", "Architecture", "City Life", "Internships"],
    advisorRecommendationRate: null,
    advisorRedFlags: [],
    advisorHighlights: [],
    hiddenCosts: ["Nightlife / entertainment (substantial)", "Day trips to Montserrat, Costa Brava"],
    applicationWindows: [
      { term: "Fall", deadline: "2025-05-01" },
      { term: "Spring", deadline: "2025-11-01" },
    ],
    scholarships: [
      { name: "API Merit Award", amount: 1000 },
    ],
    programUrl: "https://apiabroad.com/programs/spain/barcelona/",
    lastUpdated: "2025-01-15",
  },

  // ── ITALY ────────────────────────────────────────────────────────────
  {
    id: "ies-rome",
    name: "IES Abroad Rome",
    provider: "IES Abroad",
    city: "Rome",
    country: "Italy",
    countryCode: "IT",
    flag: "🇮🇹",
    cost: {
      programFee: 15600,
      housingEstimate: 3900,
      foodEstimate: 2200,
      flightEstimate: 850,
      visaFee: 50,
      insuranceRequired: 310,
      total: 22910,
    },
    stateDeptAdvisoryLevel: 2,
    crimeIndex: 41.8,
    safetyNotes: "Level 2 due to terrorism awareness; day-to-day safety for students is high.",
    soloFemaleSafetyScore: 7.0,
    fieldsOfStudy: ["Art History", "Architecture", "Italian", "Fashion", "Culinary Arts"],
    durationOptions: ["summer", "semester", "year"],
    creditTransferRate: 88,
    pellGrantEligible: true,
    financialAidAccepted: true,
    languageBarrierScore: 5,
    lgbtqTier: "caution",
    housingOptions: ["dorm", "apartment"],
    internshipsAvailable: true,
    coopEligible: false,
    rating: 4.6,
    reviewCount: 912,
    grade: "A",
    blurb: "Top pick for art history, fashion, and culinary students. IES has 50+ years in Rome — faculty connections to museums and ateliers are unmatched.",
    tags: ["Art & Design", "Culinary", "Fashion", "Summer Available", "Long-established"],
    advisorRecommendationRate: null,
    advisorRedFlags: [],
    advisorHighlights: [],
    hiddenCosts: ["Museum entry fees (non-student days)", "Gelato budget (real)", "Vespa rental for day trips"],
    applicationWindows: [
      { term: "Summer", deadline: "2025-03-15" },
      { term: "Fall", deadline: "2025-04-01" },
      { term: "Spring", deadline: "2025-10-15" },
    ],
    scholarships: [
      { name: "IES Abroad Merit Award", amount: 1500 },
      { name: "Gilman Scholarship", amount: 5000 },
    ],
    programUrl: "https://www.iesabroad.org/programs/rome",
    lastUpdated: "2025-01-15",
  },
  {
    id: "sit-florence-arts",
    name: "SIT Florence: Sustainability and the Arts",
    provider: "SIT Study Abroad",
    city: "Florence",
    country: "Italy",
    countryCode: "IT",
    flag: "🇮🇹",
    cost: {
      programFee: 17400,
      housingEstimate: 0, // housing included
      foodEstimate: 2000,
      flightEstimate: 850,
      visaFee: 50,
      insuranceRequired: 0, // insurance included
      total: 20300,
    },
    stateDeptAdvisoryLevel: 2,
    crimeIndex: 41.8,
    safetyNotes: "",
    soloFemaleSafetyScore: 7.1,
    fieldsOfStudy: ["Environmental Studies", "Art History", "Design", "Urban Studies"],
    durationOptions: ["semester"],
    creditTransferRate: 92,
    pellGrantEligible: true,
    financialAidAccepted: true,
    languageBarrierScore: 5,
    lgbtqTier: "caution",
    housingOptions: ["homestay"],
    internshipsAvailable: false,
    coopEligible: false,
    rating: 4.8,
    reviewCount: 287,
    grade: "A+",
    blurb: "Housing and insurance are included — total cost is lower than it looks. Small cohort (20–25 students) with field-based learning at artisan workshops and conservation sites.",
    tags: ["Housing Included", "Small Cohort", "Field-based", "Sustainability", "Financial Aid OK"],
    advisorRecommendationRate: null,
    advisorRedFlags: [],
    advisorHighlights: [],
    hiddenCosts: ["Train travel outside Florence", "Academic supplies (sketchbooks, materials)"],
    applicationWindows: [
      { term: "Fall", deadline: "2025-04-15" },
      { term: "Spring", deadline: "2025-11-15" },
    ],
    scholarships: [
      { name: "SIT Need-Based Award", amount: 3000 },
      { name: "Gilman Scholarship", amount: 5000 },
    ],
    programUrl: "https://studyabroad.sit.edu/programs/italy-sustainability-and-the-arts/",
    lastUpdated: "2025-01-15",
  },

  // ── JAPAN ────────────────────────────────────────────────────────────
  {
    id: "ciee-kyoto-language-culture",
    name: "CIEE Kyoto: Japanese Language & Culture",
    provider: "CIEE",
    city: "Kyoto",
    country: "Japan",
    countryCode: "JP",
    flag: "🇯🇵",
    cost: {
      programFee: 13900,
      housingEstimate: 2600,
      foodEstimate: 1800,
      flightEstimate: 1400,
      visaFee: 0,
      insuranceRequired: 350,
      total: 20050,
    },
    stateDeptAdvisoryLevel: 1,
    crimeIndex: 21.6,
    safetyNotes: "One of the safest destinations for solo travelers of any gender.",
    soloFemaleSafetyScore: 9.2,
    fieldsOfStudy: ["Japanese Language", "East Asian Studies", "Culture", "Business"],
    durationOptions: ["summer", "semester", "year"],
    creditTransferRate: 87,
    pellGrantEligible: true,
    financialAidAccepted: true,
    languageBarrierScore: 8,
    lgbtqTier: "caution",
    housingOptions: ["dorm", "homestay"],
    internshipsAvailable: false,
    coopEligible: false,
    rating: 4.9,
    reviewCount: 634,
    grade: "A+",
    blurb: "Kyoto over Tokyo for immersion — less English spoken, closer to traditional culture. Students consistently rate safety and personal growth highest of any destination.",
    tags: ["Ultra Safe", "Language Immersion", "Cultural Immersion", "Visa-Free Entry", "Low Crime"],
    advisorRecommendationRate: null,
    advisorRedFlags: [],
    advisorHighlights: [],
    hiddenCosts: ["IC card (transit ~$60/mo)", "Day trips (Nara, Osaka, Hiroshima)", "Yukata / cultural materials"],
    applicationWindows: [
      { term: "Summer", deadline: "2025-04-01" },
      { term: "Fall", deadline: "2025-04-15" },
      { term: "Spring", deadline: "2025-10-15" },
    ],
    scholarships: [
      { name: "CIEE Global Access Initiative", amount: 2000 },
      { name: "Bridging Scholarships for Study in Japan", amount: 4000 },
      { name: "Gilman Scholarship", amount: 5000 },
    ],
    programUrl: "https://www.ciee.org/go-abroad/college-study-abroad/programs/japan/kyoto",
    lastUpdated: "2025-01-15",
  },
  {
    id: "ies-tokyo-engineering",
    name: "IES Abroad Tokyo: Science, Technology & Society",
    provider: "IES Abroad",
    city: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    flag: "🇯🇵",
    cost: {
      programFee: 16200,
      housingEstimate: 3100,
      foodEstimate: 2000,
      flightEstimate: 1400,
      visaFee: 0,
      insuranceRequired: 350,
      total: 23050,
    },
    stateDeptAdvisoryLevel: 1,
    crimeIndex: 21.6,
    safetyNotes: "",
    soloFemaleSafetyScore: 9.0,
    fieldsOfStudy: ["Engineering", "Computer Science", "Robotics", "Urban Studies"],
    durationOptions: ["semester"],
    creditTransferRate: 83,
    pellGrantEligible: true,
    financialAidAccepted: true,
    languageBarrierScore: 7,
    lgbtqTier: "caution",
    housingOptions: ["dorm"],
    internshipsAvailable: true,
    coopEligible: true,
    rating: 4.7,
    reviewCount: 312,
    grade: "A+",
    blurb: "One of the few STEM-focused programs in Japan with co-op eligibility. Partners with Waseda and Keio University labs. Credit transfer rate is lower than liberal arts programs — verify your home institution's policy before applying.",
    tags: ["STEM", "Co-op Eligible", "Internships", "Waseda / Keio Access", "Ultra Safe"],
    advisorRecommendationRate: null,
    advisorRedFlags: [],
    advisorHighlights: [],
    hiddenCosts: ["Suica card (transit)", "Lab safety equipment if required", "Tokyo nightlife"],
    applicationWindows: [
      { term: "Fall", deadline: "2025-04-01" },
      { term: "Spring", deadline: "2025-10-01" },
    ],
    scholarships: [
      { name: "Bridging Scholarships for Study in Japan", amount: 4000 },
      { name: "IES Abroad Merit Award", amount: 1500 },
    ],
    programUrl: "https://www.iesabroad.org/programs/tokyo",
    lastUpdated: "2025-01-15",
  },

  // ── GERMANY ──────────────────────────────────────────────────────────
  {
    id: "ciee-berlin-arts-sciences",
    name: "CIEE Berlin: Arts & Sciences",
    provider: "CIEE",
    city: "Berlin",
    country: "Germany",
    countryCode: "DE",
    flag: "🇩🇪",
    cost: {
      programFee: 14100,
      housingEstimate: 3200,
      foodEstimate: 1900,
      flightEstimate: 850,
      visaFee: 75,
      insuranceRequired: 300,
      total: 20425,
    },
    stateDeptAdvisoryLevel: 2,
    crimeIndex: 30.4,
    safetyNotes: "Level 2 advisory is terrorism-related; student-level safety is high.",
    soloFemaleSafetyScore: 7.9,
    fieldsOfStudy: ["Political Science", "Film", "Music", "German", "History", "Tech"],
    durationOptions: ["semester", "year"],
    creditTransferRate: 90,
    pellGrantEligible: true,
    financialAidAccepted: true,
    languageBarrierScore: 4,
    lgbtqTier: "generally safe",
    housingOptions: ["dorm", "apartment"],
    internshipsAvailable: true,
    coopEligible: false,
    rating: 4.6,
    reviewCount: 578,
    grade: "A",
    blurb: "Berlin punches well above its weight for arts, tech, and political science students. Europe's cheapest major capital — a semester here costs less than a summer in Paris.",
    tags: ["Low Cost for Europe", "LGBTQ+ Safe", "Tech Scene", "Arts", "Internships"],
    advisorRecommendationRate: null,
    advisorRedFlags: [],
    advisorHighlights: [],
    hiddenCosts: ["BVG transit pass (~€90/mo not always covered)", "Club entry / Berlin nightlife"],
    applicationWindows: [
      { term: "Fall", deadline: "2025-04-01" },
      { term: "Spring", deadline: "2025-10-15" },
    ],
    scholarships: [
      { name: "CIEE Global Access Initiative", amount: 2000 },
      { name: "DAAD RISE Professional (separate)", amount: 0 },
    ],
    programUrl: "https://www.ciee.org/go-abroad/college-study-abroad/programs/germany/berlin",
    lastUpdated: "2025-01-15",
  },

  // ── SOUTH AFRICA ─────────────────────────────────────────────────────
  {
    id: "sit-cape-town-social-justice",
    name: "SIT Cape Town: Social Justice & Transformation",
    provider: "SIT Study Abroad",
    city: "Cape Town",
    country: "South Africa",
    countryCode: "ZA",
    flag: "🇿🇦",
    cost: {
      programFee: 17800,
      housingEstimate: 0, // included
      foodEstimate: 1200,
      flightEstimate: 1600,
      visaFee: 0,
      insuranceRequired: 0, // included
      total: 20600,
    },
    stateDeptAdvisoryLevel: 2,
    crimeIndex: 76.2,
    safetyNotes: "High crime index nationally but the program operates with structured safety protocols; students are oriented extensively on neighborhood awareness.",
    soloFemaleSafetyScore: 5.8,
    fieldsOfStudy: ["Political Science", "Sociology", "Public Health", "African Studies"],
    durationOptions: ["semester"],
    creditTransferRate: 94,
    pellGrantEligible: true,
    financialAidAccepted: true,
    languageBarrierScore: 1,
    lgbtqTier: "generally safe",
    housingOptions: ["homestay"],
    internshipsAvailable: true,
    coopEligible: false,
    rating: 4.8,
    reviewCount: 201,
    grade: "A+",
    blurb: "Housing, insurance, and most meals are included — the true cost is lower than the program fee implies. Best for students in public health, political science, or African studies who want field-based learning. Safety requires awareness but the program's track record is strong.",
    tags: ["Housing Included", "Field-based", "Social Justice", "Public Health", "Africa"],
    advisorRecommendationRate: null,
    advisorRedFlags: ["Safety awareness is non-negotiable — not suitable for students who dismiss briefings"],
    advisorHighlights: ["Transformative for public policy and public health students"],
    hiddenCosts: ["Safari/nature excursions (optional but popular)", "International SIM card"],
    applicationWindows: [
      { term: "Fall", deadline: "2025-04-01" },
      { term: "Spring", deadline: "2025-11-01" },
    ],
    scholarships: [
      { name: "SIT Need-Based Award", amount: 3000 },
      { name: "Gilman Scholarship", amount: 5000 },
    ],
    programUrl: "https://studyabroad.sit.edu/programs/south-africa-social-justice/",
    lastUpdated: "2025-01-15",
  },

  // ── GHANA ─────────────────────────────────────────────────────────────
  {
    id: "ciee-accra-arts-sciences",
    name: "CIEE Accra: Arts & Sciences",
    provider: "CIEE",
    city: "Accra",
    country: "Ghana",
    countryCode: "GH",
    flag: "🇬🇭",
    cost: {
      programFee: 11400,
      housingEstimate: 1800,
      foodEstimate: 800,
      flightEstimate: 1700,
      visaFee: 60,
      insuranceRequired: 320,
      total: 16080,
    },
    stateDeptAdvisoryLevel: 2,
    crimeIndex: 45.3,
    safetyNotes: "Level 2 advisory; Accra is among the safest sub-Saharan capitals for students. Program provides comprehensive safety orientation.",
    soloFemaleSafetyScore: 6.2,
    fieldsOfStudy: ["African Studies", "Political Science", "Public Health", "Journalism"],
    durationOptions: ["semester"],
    creditTransferRate: 86,
    pellGrantEligible: true,
    financialAidAccepted: true,
    languageBarrierScore: 0,
    lgbtqTier: "hostile",
    housingOptions: ["dorm", "homestay"],
    internshipsAvailable: false,
    coopEligible: false,
    rating: 4.5,
    reviewCount: 189,
    grade: "A",
    blurb: "One of the most affordable programs that accepts Pell grants. English-speaking but true cultural immersion. LGBTQ+ students should research the legal and social climate carefully before applying.",
    tags: ["Lowest Cost", "Financial Aid OK", "English-speaking", "Africa", "Cultural Immersion"],
    advisorRecommendationRate: null,
    advisorRedFlags: ["Not recommended for openly LGBTQ+ students — same-sex relationships are criminalized"],
    advisorHighlights: ["Exceptional value for journalism and African studies majors"],
    hiddenCosts: ["Malaria prophylaxis (~$100)", "Yellow fever vaccination (required)", "Mosquito nets if homestay"],
    applicationWindows: [
      { term: "Fall", deadline: "2025-04-15" },
      { term: "Spring", deadline: "2025-11-01" },
    ],
    scholarships: [
      { name: "CIEE Global Access Initiative", amount: 2000 },
      { name: "Gilman Scholarship", amount: 5000 },
    ],
    programUrl: "https://www.ciee.org/go-abroad/college-study-abroad/programs/ghana/accra",
    lastUpdated: "2025-01-15",
  },

  // ── CHILE ─────────────────────────────────────────────────────────────
  {
    id: "ciee-santiago-liberal-arts",
    name: "CIEE Santiago: Liberal Arts",
    provider: "CIEE",
    city: "Santiago",
    country: "Chile",
    countryCode: "CL",
    flag: "🇨🇱",
    cost: {
      programFee: 12800,
      housingEstimate: 2400,
      foodEstimate: 1600,
      flightEstimate: 1100,
      visaFee: 0,
      insuranceRequired: 290,
      total: 18190,
    },
    stateDeptAdvisoryLevel: 1,
    crimeIndex: 47.1,
    safetyNotes: "",
    soloFemaleSafetyScore: 6.8,
    fieldsOfStudy: ["Spanish", "Political Science", "Environmental Studies", "Latin American Studies"],
    durationOptions: ["semester", "year"],
    creditTransferRate: 88,
    pellGrantEligible: true,
    financialAidAccepted: true,
    languageBarrierScore: 7,
    lgbtqTier: "caution",
    housingOptions: ["homestay", "apartment"],
    internshipsAvailable: false,
    coopEligible: false,
    rating: 4.5,
    reviewCount: 342,
    grade: "A",
    blurb: "Santiago is the most accessible South American capital for first-time international travelers — safe, modern infrastructure, and excellent Spanish immersion without the chaos of Buenos Aires.",
    tags: ["Spanish Immersion", "Low Cost", "Visa-Free", "Latin America", "Financial Aid OK"],
    advisorRecommendationRate: null,
    advisorRedFlags: [],
    advisorHighlights: [],
    hiddenCosts: ["Bip! transit card (~$40/mo)", "Weekend trips to Patagonia / Easter Island"],
    applicationWindows: [
      { term: "Fall", deadline: "2025-04-15" },
      { term: "Spring", deadline: "2025-10-15" },
    ],
    scholarships: [
      { name: "CIEE Global Access Initiative", amount: 2000 },
      { name: "Gilman Scholarship", amount: 5000 },
    ],
    programUrl: "https://www.ciee.org/go-abroad/college-study-abroad/programs/chile/santiago",
    lastUpdated: "2025-01-15",
  },

  // ── COSTA RICA ────────────────────────────────────────────────────────
  {
    id: "sit-costa-rica-environment",
    name: "SIT Costa Rica: Sustainability & Environmental Policy",
    provider: "SIT Study Abroad",
    city: "San José",
    country: "Costa Rica",
    countryCode: "CR",
    flag: "🇨🇷",
    cost: {
      programFee: 17200,
      housingEstimate: 0, // included
      foodEstimate: 0,   // included
      flightEstimate: 600,
      visaFee: 0,
      insuranceRequired: 0, // included
      total: 17800,
    },
    stateDeptAdvisoryLevel: 1,
    crimeIndex: 48.2,
    safetyNotes: "",
    soloFemaleSafetyScore: 7.0,
    fieldsOfStudy: ["Environmental Studies", "Biology", "Policy", "Sustainability"],
    durationOptions: ["semester"],
    creditTransferRate: 95,
    pellGrantEligible: true,
    financialAidAccepted: true,
    languageBarrierScore: 5,
    lgbtqTier: "generally safe",
    housingOptions: ["homestay"],
    internshipsAvailable: false,
    coopEligible: false,
    rating: 4.9,
    reviewCount: 318,
    grade: "A+",
    blurb: "Housing, meals, and insurance all included — this is one of the best true-cost values in the SIT portfolio. Field-based curriculum means you spend more time in cloud forests and policy offices than classrooms.",
    tags: ["All-Inclusive", "Best True Cost Value", "STEM", "Environment", "Field-based", "LGBTQ+ Safe"],
    advisorRecommendationRate: null,
    advisorRedFlags: [],
    advisorHighlights: ["Best-in-class for environmental science field work"],
    hiddenCosts: ["Personal souvenirs", "Independent weekend travel"],
    applicationWindows: [
      { term: "Fall", deadline: "2025-04-15" },
      { term: "Spring", deadline: "2025-11-01" },
    ],
    scholarships: [
      { name: "SIT Need-Based Award", amount: 3000 },
      { name: "Gilman Scholarship", amount: 5000 },
    ],
    programUrl: "https://studyabroad.sit.edu/programs/costa-rica-sustainability-and-environmental-policy/",
    lastUpdated: "2025-01-15",
  },

  // ── PORTUGAL ──────────────────────────────────────────────────────────
  {
    id: "ciee-lisbon-liberal-arts",
    name: "CIEE Lisbon: Liberal Arts",
    provider: "CIEE",
    city: "Lisbon",
    country: "Portugal",
    countryCode: "PT",
    flag: "🇵🇹",
    cost: {
      programFee: 13400,
      housingEstimate: 2900,
      foodEstimate: 1700,
      flightEstimate: 820,
      visaFee: 90,
      insuranceRequired: 290,
      total: 19200,
    },
    stateDeptAdvisoryLevel: 1,
    crimeIndex: 27.6,
    safetyNotes: "One of the lowest crime rates in Western Europe.",
    soloFemaleSafetyScore: 8.4,
    fieldsOfStudy: ["Business", "Portuguese", "History", "Architecture", "Urban Studies"],
    durationOptions: ["semester", "year"],
    creditTransferRate: 90,
    pellGrantEligible: true,
    financialAidAccepted: true,
    languageBarrierScore: 3,
    lgbtqTier: "generally safe",
    housingOptions: ["apartment", "dorm"],
    internshipsAvailable: true,
    coopEligible: false,
    rating: 4.7,
    reviewCount: 421,
    grade: "A+",
    blurb: "Europe's best-kept secret for value — Lisbon offers Western European safety and quality at Eastern European prices. English is widely spoken; LGBTQ+ legal protections are among Europe's strongest.",
    tags: ["Best Value in Europe", "Ultra Safe", "LGBTQ+ Safe", "English OK", "Internships"],
    advisorRecommendationRate: null,
    advisorRedFlags: [],
    advisorHighlights: [],
    hiddenCosts: ["Tram 28 tourist taxes (use metro instead)", "Airfare via Azores if connecting through Boston"],
    applicationWindows: [
      { term: "Fall", deadline: "2025-04-01" },
      { term: "Spring", deadline: "2025-10-15" },
    ],
    scholarships: [
      { name: "CIEE Global Access Initiative", amount: 2000 },
      { name: "Gilman Scholarship", amount: 5000 },
    ],
    programUrl: "https://www.ciee.org/go-abroad/college-study-abroad/programs/portugal/lisbon",
    lastUpdated: "2025-01-15",
  },

  // ── TAIWAN ────────────────────────────────────────────────────────────
  {
    id: "iclp-taipei-chinese",
    name: "ICLP Taipei: Intensive Chinese Language",
    provider: "Inter-University Program for Chinese Language Studies",
    city: "Taipei",
    country: "Taiwan",
    countryCode: "TW",
    flag: "🇹🇼",
    cost: {
      programFee: 5800,
      housingEstimate: 2200,
      foodEstimate: 1200,
      flightEstimate: 1300,
      visaFee: 0,
      insuranceRequired: 200,
      total: 10700,
    },
    stateDeptAdvisoryLevel: 2,
    crimeIndex: 23.1,
    safetyNotes: "Level 2 due to regional tensions with China; on-the-ground safety for students is excellent.",
    soloFemaleSafetyScore: 9.0,
    fieldsOfStudy: ["Mandarin Chinese", "East Asian Studies", "Business"],
    durationOptions: ["summer", "semester", "year"],
    creditTransferRate: 96,
    pellGrantEligible: false,
    financialAidAccepted: false,
    languageBarrierScore: 9,
    lgbtqTier: "generally safe",
    housingOptions: ["dorm", "apartment", "independent"],
    internshipsAvailable: false,
    coopEligible: false,
    rating: 4.9,
    reviewCount: 267,
    grade: "A+",
    blurb: "The gold standard for Mandarin acquisition — ICLP is where linguistics professors send their best students. Lowest total cost of any program in Asia by a wide margin. Taiwan is the most LGBTQ+-affirming country in Asia.",
    tags: ["Lowest Cost in Asia", "Language Immersion", "Mandarin", "LGBTQ+ Safe Asia", "Ultra Safe"],
    advisorRecommendationRate: null,
    advisorRedFlags: ["No Title IV aid — need private scholarships or out-of-pocket"],
    advisorHighlights: ["Best Mandarin program in the world at this price point"],
    hiddenCosts: ["EasyCard transit (~$30/mo)", "Scooter rental if living off-campus"],
    applicationWindows: [
      { term: "Summer", deadline: "2025-02-15" },
      { term: "Fall", deadline: "2025-04-01" },
      { term: "Spring", deadline: "2025-10-01" },
    ],
    scholarships: [
      { name: "Taiwan MOE Huayu Enrichment Scholarship", amount: 800 },
    ],
    programUrl: "https://iclp.ntu.edu.tw/",
    lastUpdated: "2025-01-15",
  },

  // ── MOROCCO ───────────────────────────────────────────────────────────
  {
    id: "sit-rabat-language-culture",
    name: "SIT Morocco: Language, Culture & Society",
    provider: "SIT Study Abroad",
    city: "Rabat",
    country: "Morocco",
    countryCode: "MA",
    flag: "🇲🇦",
    cost: {
      programFee: 16900,
      housingEstimate: 0, // included
      foodEstimate: 0,   // included
      flightEstimate: 900,
      visaFee: 0,
      insuranceRequired: 0, // included
      total: 17800,
    },
    stateDeptAdvisoryLevel: 2,
    crimeIndex: 46.8,
    safetyNotes: "Level 2 terrorism advisory; students report personal safety is generally high in Rabat with the program's structured activities.",
    soloFemaleSafetyScore: 5.5,
    fieldsOfStudy: ["Arabic", "African Studies", "Political Science", "Islamic Studies"],
    durationOptions: ["semester"],
    creditTransferRate: 91,
    pellGrantEligible: true,
    financialAidAccepted: true,
    languageBarrierScore: 9,
    lgbtqTier: "hostile",
    housingOptions: ["homestay"],
    internshipsAvailable: false,
    coopEligible: false,
    rating: 4.6,
    reviewCount: 178,
    grade: "A",
    blurb: "All-inclusive and strong for Arabic language acquisition and North African political studies. LGBTQ+ students should know same-sex relations are criminalized. Solo women report more street harassment than in European destinations — program provides strong support.",
    tags: ["All-Inclusive", "Arabic Immersion", "Africa", "Financial Aid OK", "Islamic Studies"],
    advisorRecommendationRate: null,
    advisorRedFlags: [
      "Not suitable for openly LGBTQ+ students",
      "Solo female students need to follow program dress/safety guidelines closely",
    ],
    advisorHighlights: ["Outstanding for Arabic language immersion at an all-inclusive price"],
    hiddenCosts: ["Medina shopping (souvenirs)", "Day trips to Fez, Marrakech"],
    applicationWindows: [
      { term: "Fall", deadline: "2025-04-15" },
      { term: "Spring", deadline: "2025-11-01" },
    ],
    scholarships: [
      { name: "SIT Need-Based Award", amount: 3000 },
      { name: "Gilman Scholarship", amount: 5000 },
    ],
    programUrl: "https://studyabroad.sit.edu/programs/morocco-language-culture-and-society/",
    lastUpdated: "2025-01-15",
  },
];

// ── Destination summaries ────────────────────────────────────────────────────
const DESTINATIONS: Destination[] = IIE_TOP_DESTINATIONS.map((d) => ({
  country: d.country,
  countryCode: d.countryCode,
  flag: d.flag,
  programCount: d.programCount,
  gradient: d.gradient,
  stateDeptAdvisoryLevel: 1 as const, // overridden at runtime from country-data.json
  crimeIndex: 0,
  costOfLivingIndex: 0,
  lgbtqTier: "caution" as const,
  topFieldsOfStudy: [],
}));

// ── Write ────────────────────────────────────────────────────────────────────
function main() {
  fs.mkdirSync(path.dirname(PROGRAMS_OUT), { recursive: true });
  fs.writeFileSync(
    PROGRAMS_OUT,
    JSON.stringify(
      { generatedAt: new Date().toISOString(), programs: REAL_PROGRAMS },
      null,
      2
    )
  );
  fs.writeFileSync(
    DESTINATIONS_OUT,
    JSON.stringify(
      { generatedAt: new Date().toISOString(), destinations: DESTINATIONS },
      null,
      2
    )
  );
  console.log(`Seeded ${REAL_PROGRAMS.length} programs → ${PROGRAMS_OUT}`);
  console.log(`Seeded ${DESTINATIONS.length} destinations → ${DESTINATIONS_OUT}`);
}

main();
