/**
 * Seed list of US universities with their study abroad office URLs.
 * Covers large public flagships, small liberal arts colleges, HBCUs,
 * technical schools, and regional schools — intentionally diverse.
 * Excludes the 5C colleges (Pomona, Harvey Mudd, Scripps, Pitzer, CMC).
 *
 * Used by scrape-advisor-contacts.ts to pull advisor names and emails.
 */

export type SchoolType =
  | "large-public"
  | "small-liberal-arts"
  | "hbcu"
  | "tech"
  | "regional"
  | "research"
  | "scorecard"; // auto-generated from College Scorecard

export type SchoolSeed = {
  school: string;
  type: SchoolType;
  studyAbroadUrl: string;
};

export const SCHOOL_SEEDS: SchoolSeed[] = [
  // ── Large Public Flagships ────────────────────────────────────────────
  { school: "University of Michigan", type: "large-public", studyAbroadUrl: "https://isp.umich.edu/study-abroad/find-a-program/" },
  { school: "University of California Berkeley", type: "large-public", studyAbroadUrl: "https://studyabroad.berkeley.edu/contact" },
  { school: "University of California Los Angeles", type: "large-public", studyAbroadUrl: "https://ieo.ucla.edu/contact" },
  { school: "University of Texas Austin", type: "large-public", studyAbroadUrl: "https://world.utexas.edu/abroad/contact" },
  { school: "University of Wisconsin Madison", type: "large-public", studyAbroadUrl: "https://international.wisc.edu/study-abroad/contact/" },
  { school: "University of Illinois Urbana-Champaign", type: "large-public", studyAbroadUrl: "https://studyabroad.illinois.edu/about/staff/" },
  { school: "University of Washington", type: "large-public", studyAbroadUrl: "https://studyabroad.washington.edu/contact/" },
  { school: "University of Florida", type: "large-public", studyAbroadUrl: "https://ufic.ufl.edu/study-abroad/contact/" },
  { school: "Ohio State University", type: "large-public", studyAbroadUrl: "https://oia.osu.edu/study-abroad/contact-us/" },
  { school: "Penn State University", type: "large-public", studyAbroadUrl: "https://global.psu.edu/content/contact-education-abroad" },
  { school: "University of Minnesota", type: "large-public", studyAbroadUrl: "https://umabroad.umn.edu/students/advising" },
  { school: "Indiana University", type: "large-public", studyAbroadUrl: "https://overseas.iu.edu/contacts/index.html" },
  { school: "Michigan State University", type: "large-public", studyAbroadUrl: "https://studyabroad.msu.edu/about/contact.html" },
  { school: "University of Georgia", type: "large-public", studyAbroadUrl: "https://studyabroad.uga.edu/contact/" },
  { school: "University of Colorado Boulder", type: "large-public", studyAbroadUrl: "https://www.colorado.edu/studyabroad/contact" },
  { school: "University of Arizona", type: "large-public", studyAbroadUrl: "https://global.arizona.edu/study-abroad" },
  { school: "University of Virginia", type: "large-public", studyAbroadUrl: "https://ias.virginia.edu/study-abroad/contact" },
  { school: "University of North Carolina Chapel Hill", type: "large-public", studyAbroadUrl: "https://studyabroad.unc.edu/contact/" },
  { school: "University of Maryland", type: "large-public", studyAbroadUrl: "https://global.umd.edu/education-abroad/contact" },
  { school: "Rutgers University", type: "large-public", studyAbroadUrl: "https://global.rutgers.edu/study-abroad/contact" },
  { school: "University of Pittsburgh", type: "large-public", studyAbroadUrl: "https://www.abroad.pitt.edu/contact" },
  { school: "University of Iowa", type: "large-public", studyAbroadUrl: "https://studyabroad.uiowa.edu/contact" },
  { school: "Iowa State University", type: "large-public", studyAbroadUrl: "https://www.studyabroad.iastate.edu/contact" },
  { school: "University of Missouri", type: "large-public", studyAbroadUrl: "https://international.missouri.edu/go-abroad/contact.php" },
  { school: "Arizona State University", type: "large-public", studyAbroadUrl: "https://goglobal.asu.edu/contact" },
  { school: "Florida State University", type: "large-public", studyAbroadUrl: "https://studyabroad.fsu.edu/contact" },
  { school: "University of Tennessee", type: "large-public", studyAbroadUrl: "https://studyabroad.utk.edu/contact/" },
  { school: "University of South Carolina", type: "large-public", studyAbroadUrl: "https://sc.edu/about/offices_and_divisions/study_abroad/contact/index.php" },
  { school: "University of Oregon", type: "large-public", studyAbroadUrl: "https://international.uoregon.edu/studyabroad_contact" },
  { school: "University of Kansas", type: "large-public", studyAbroadUrl: "https://abroad.ku.edu/contact-us" },
  { school: "Purdue University", type: "large-public", studyAbroadUrl: "https://www.purdue.edu/cie/studyabroad/contactus.html" },
  { school: "University of Nebraska", type: "large-public", studyAbroadUrl: "https://global.unl.edu/study-abroad/contact" },
  { school: "University of Oklahoma", type: "large-public", studyAbroadUrl: "https://global.ou.edu/study-abroad/contact" },
  { school: "University of Arkansas", type: "large-public", studyAbroadUrl: "https://studyabroad.uark.edu/contact/index.php" },
  { school: "Texas A&M University", type: "large-public", studyAbroadUrl: "https://studyabroad.tamu.edu/index.cfm?FuseAction=Abroad.ViewLink&Link_ID=5B3B7A29-5056-BA1F-7482F2C1C5B19D25" },
  { school: "Virginia Tech", type: "large-public", studyAbroadUrl: "https://global.vt.edu/education_abroad/contact.html" },
  { school: "North Carolina State University", type: "large-public", studyAbroadUrl: "https://global.ncsu.edu/study-abroad/" },
  { school: "University of Kentucky", type: "large-public", studyAbroadUrl: "https://international.uky.edu/EA" },
  { school: "University of Alabama", type: "large-public", studyAbroadUrl: "https://international.ua.edu/studyabroad/contact/" },
  { school: "University of Mississippi", type: "large-public", studyAbroadUrl: "https://international.olemiss.edu/study-abroad/" },
  { school: "Louisiana State University", type: "large-public", studyAbroadUrl: "https://www.lsu.edu/studyabroad/contactus.php" },
  { school: "University of Connecticut", type: "large-public", studyAbroadUrl: "https://studyabroad.uconn.edu/contact/" },
  { school: "University of Massachusetts Amherst", type: "large-public", studyAbroadUrl: "https://www.umass.edu/studyabroad/contact" },
  { school: "University of New Hampshire", type: "large-public", studyAbroadUrl: "https://cola.unh.edu/study-abroad/contact" },
  { school: "University of Vermont", type: "large-public", studyAbroadUrl: "https://www.uvm.edu/studyabroad/contact" },
  { school: "University of Maine", type: "large-public", studyAbroadUrl: "https://umaine.edu/studyabroad/contact/" },
  { school: "University of Rhode Island", type: "large-public", studyAbroadUrl: "https://web.uri.edu/international/studying-abroad/" },
  { school: "University of Delaware", type: "large-public", studyAbroadUrl: "https://www.udel.edu/academics/global/study-abroad/" },
  { school: "University of Nevada Las Vegas", type: "large-public", studyAbroadUrl: "https://www.unlv.edu/studyabroad/contact" },
  { school: "University of Hawaii Manoa", type: "large-public", studyAbroadUrl: "https://www.hawaii.edu/studyabroad/" },

  // ── Private Research Universities ─────────────────────────────────────
  { school: "Harvard University", type: "research", studyAbroadUrl: "https://www.harvard.edu/academics/international-study/" },
  { school: "Yale University", type: "research", studyAbroadUrl: "https://yalecollege.yale.edu/academics/study-abroad" },
  { school: "Princeton University", type: "research", studyAbroadUrl: "https://international.princeton.edu/studying-abroad" },
  { school: "Columbia University", type: "research", studyAbroadUrl: "https://globalstudies.columbia.edu/study-abroad" },
  { school: "University of Pennsylvania", type: "research", studyAbroadUrl: "https://global.upenn.edu/isss/study-abroad" },
  { school: "Duke University", type: "research", studyAbroadUrl: "https://globaleduc.duke.edu/study-abroad/contact/" },
  { school: "Northwestern University", type: "research", studyAbroadUrl: "https://abroad.northwestern.edu/contact" },
  { school: "Georgetown University", type: "research", studyAbroadUrl: "https://studyabroad.georgetown.edu/contact/" },
  { school: "Vanderbilt University", type: "research", studyAbroadUrl: "https://www.vanderbilt.edu/oacs/study-abroad/contact.php" },
  { school: "Rice University", type: "research", studyAbroadUrl: "https://oip.rice.edu/study-abroad/contact-us" },
  { school: "Washington University St. Louis", type: "research", studyAbroadUrl: "https://studyabroad.wustl.edu/contact" },
  { school: "Emory University", type: "research", studyAbroadUrl: "https://studyabroad.emory.edu/index.cfm?FuseAction=Abroad.ViewLink&Link_ID=2BF06C69-5056-BA1F-74A4E2B4B1A4D4AC" },
  { school: "Notre Dame University", type: "research", studyAbroadUrl: "https://iisabroad.nd.edu/contact/" },
  { school: "Tufts University", type: "research", studyAbroadUrl: "https://studyabroad.tufts.edu/contact" },
  { school: "Boston University", type: "research", studyAbroadUrl: "https://www.bu.edu/abroad/contact/" },
  { school: "New York University", type: "research", studyAbroadUrl: "https://www.nyu.edu/students/student-information-and-resources/study-abroad.html" },
  { school: "University of Southern California", type: "research", studyAbroadUrl: "https://ois.usc.edu/study-abroad/contact/" },
  { school: "Tulane University", type: "research", studyAbroadUrl: "https://studyabroad.tulane.edu/contact" },
  { school: "Case Western Reserve University", type: "research", studyAbroadUrl: "https://studyabroad.case.edu/contact" },
  { school: "American University", type: "research", studyAbroadUrl: "https://www.american.edu/ocl/studyabroad/contact.cfm" },
  { school: "George Washington University", type: "research", studyAbroadUrl: "https://studyabroad.gwu.edu/contact-us" },
  { school: "Johns Hopkins University", type: "research", studyAbroadUrl: "https://studyabroad.jhu.edu/contact/" },
  { school: "University of Rochester", type: "research", studyAbroadUrl: "https://www.rochester.edu/college/study-abroad/contact/" },
  { school: "Syracuse University", type: "research", studyAbroadUrl: "https://suabroad.syr.edu/contact/" },
  { school: "Fordham University", type: "research", studyAbroadUrl: "https://www.fordham.edu/info/20527/study_abroad" },
  { school: "Loyola University Chicago", type: "research", studyAbroadUrl: "https://www.luc.edu/studyabroad/contact/" },
  { school: "Marquette University", type: "research", studyAbroadUrl: "https://www.marquette.edu/study-abroad/contact.php" },
  { school: "Santa Clara University", type: "research", studyAbroadUrl: "https://www.scu.edu/globalengagement/study-abroad/contact/" },
  { school: "University of San Francisco", type: "research", studyAbroadUrl: "https://www.usfca.edu/international/study-abroad/contact" },
  { school: "University of Denver", type: "research", studyAbroadUrl: "https://www.du.edu/abroad/contact" },
  { school: "Drexel University", type: "research", studyAbroadUrl: "https://drexel.edu/studyabroad/contact/" },
  { school: "Temple University", type: "research", studyAbroadUrl: "https://studyabroad.temple.edu/contact" },
  { school: "Northeastern University", type: "research", studyAbroadUrl: "https://globalexperience.northeastern.edu/contact/" },

  // ── Small Liberal Arts Colleges (non-5C) ──────────────────────────────
  { school: "Amherst College", type: "small-liberal-arts", studyAbroadUrl: "https://www.amherst.edu/academiclife/global/studyabroad/contact" },
  { school: "Williams College", type: "small-liberal-arts", studyAbroadUrl: "https://dean.williams.edu/fellowships-and-study-abroad/study-abroad/contact-us/" },
  { school: "Swarthmore College", type: "small-liberal-arts", studyAbroadUrl: "https://www.swarthmore.edu/academic-advising-support/study-abroad" },
  { school: "Bowdoin College", type: "small-liberal-arts", studyAbroadUrl: "https://www.bowdoin.edu/off-campus-study/contact.html" },
  { school: "Middlebury College", type: "small-liberal-arts", studyAbroadUrl: "https://www.middlebury.edu/office/international-programs/study-abroad" },
  { school: "Colby College", type: "small-liberal-arts", studyAbroadUrl: "https://www.colby.edu/off-campus-study/contact/" },
  { school: "Colgate University", type: "small-liberal-arts", studyAbroadUrl: "https://www.colgate.edu/academics/off-campus-study/contact" },
  { school: "Hamilton College", type: "small-liberal-arts", studyAbroadUrl: "https://www.hamilton.edu/academics/off-campus-study" },
  { school: "Vassar College", type: "small-liberal-arts", studyAbroadUrl: "https://offices.vassar.edu/international-studies/study-abroad/contact/" },
  { school: "Wesleyan University", type: "small-liberal-arts", studyAbroadUrl: "https://www.wesleyan.edu/ois/studyabroad/" },
  { school: "Trinity College Hartford", type: "small-liberal-arts", studyAbroadUrl: "https://www.trincoll.edu/academics/global-learning/study-abroad/" },
  { school: "Bates College", type: "small-liberal-arts", studyAbroadUrl: "https://www.bates.edu/off-campus-study/contact-us/" },
  { school: "Oberlin College", type: "small-liberal-arts", studyAbroadUrl: "https://www.oberlin.edu/study-away-and-programs-abroad/contact" },
  { school: "Grinnell College", type: "small-liberal-arts", studyAbroadUrl: "https://www.grinnell.edu/academics/dean/oar/study-abroad/contact" },
  { school: "Carleton College", type: "small-liberal-arts", studyAbroadUrl: "https://apps.carleton.edu/global_ed/contact/" },
  { school: "Macalester College", type: "small-liberal-arts", studyAbroadUrl: "https://www.macalester.edu/international-programs/study-abroad/contact/" },
  { school: "Bryn Mawr College", type: "small-liberal-arts", studyAbroadUrl: "https://www.brynmawr.edu/inside/offices-services/global-initiatives/study-abroad" },
  { school: "Mount Holyoke College", type: "small-liberal-arts", studyAbroadUrl: "https://www.mtholyoke.edu/global/study-abroad/contact" },
  { school: "Smith College", type: "small-liberal-arts", studyAbroadUrl: "https://www.smith.edu/academics/study-abroad" },
  { school: "Wellesley College", type: "small-liberal-arts", studyAbroadUrl: "https://www.wellesley.edu/ois/studyabroad" },
  { school: "Barnard College", type: "small-liberal-arts", studyAbroadUrl: "https://barnard.edu/global-education/study-abroad-away/contact" },
  { school: "Skidmore College", type: "small-liberal-arts", studyAbroadUrl: "https://www.skidmore.edu/international-programs/study-abroad.php" },
  { school: "Union College", type: "small-liberal-arts", studyAbroadUrl: "https://www.union.edu/international-programs/study-abroad" },
  { school: "Bucknell University", type: "small-liberal-arts", studyAbroadUrl: "https://www.bucknell.edu/life-bucknell/global-education/education-abroad/contact" },
  { school: "Lafayette College", type: "small-liberal-arts", studyAbroadUrl: "https://international.lafayette.edu/study-abroad/contact/" },
  { school: "Gettysburg College", type: "small-liberal-arts", studyAbroadUrl: "https://www.gettysburg.edu/off-campus-study/contact/" },
  { school: "Denison University", type: "small-liberal-arts", studyAbroadUrl: "https://denison.edu/campus/global-programs/study-away" },
  { school: "Kenyon College", type: "small-liberal-arts", studyAbroadUrl: "https://www.kenyon.edu/academics/academic-resources/study-abroad-away/contact-us/" },
  { school: "College of Wooster", type: "small-liberal-arts", studyAbroadUrl: "https://www.wooster.edu/academics/global/contact/" },
  { school: "Wabash College", type: "small-liberal-arts", studyAbroadUrl: "https://www.wabash.edu/academics/off-campus-study/" },
  { school: "DePauw University", type: "small-liberal-arts", studyAbroadUrl: "https://www.depauw.edu/academics/global/contact/" },
  { school: "Allegheny College", type: "small-liberal-arts", studyAbroadUrl: "https://sites.allegheny.edu/off-campus-study/contact/" },
  { school: "Dickinson College", type: "small-liberal-arts", studyAbroadUrl: "https://www.dickinson.edu/homepage/137/study_abroad_contact" },
  { school: "Franklin & Marshall College", type: "small-liberal-arts", studyAbroadUrl: "https://www.fandm.edu/off-campus-study/contact" },
  { school: "Muhlenberg College", type: "small-liberal-arts", studyAbroadUrl: "https://www.muhlenberg.edu/main/academics/international/abroad/" },
  { school: "Connecticut College", type: "small-liberal-arts", studyAbroadUrl: "https://www.conncoll.edu/academics/centers/international-programs-and-connected-learning/" },
  { school: "Rhodes College", type: "small-liberal-arts", studyAbroadUrl: "https://www.rhodes.edu/academics/international-programs/study-abroad" },
  { school: "Centre College", type: "small-liberal-arts", studyAbroadUrl: "https://www.centre.edu/academics/international-programs/study-abroad/" },
  { school: "Furman University", type: "small-liberal-arts", studyAbroadUrl: "https://www.furman.edu/academics/global-education-and-away-programs/contact/" },
  { school: "Davidson College", type: "small-liberal-arts", studyAbroadUrl: "https://www.davidson.edu/academics/global-education/study-abroad" },
  { school: "Earlham College", type: "small-liberal-arts", studyAbroadUrl: "https://www.earlham.edu/offices-and-services/international-programs/" },
  { school: "Whitman College", type: "small-liberal-arts", studyAbroadUrl: "https://www.whitman.edu/academics/off-campus-study/contact" },
  { school: "Reed College", type: "small-liberal-arts", studyAbroadUrl: "https://www.reed.edu/academic-support/study-abroad/" },
  { school: "Bard College", type: "small-liberal-arts", studyAbroadUrl: "https://www.bard.edu/globaleducation/contact/" },
  { school: "Sarah Lawrence College", type: "small-liberal-arts", studyAbroadUrl: "https://www.sarahlawrence.edu/study-abroad/" },
  { school: "Bennington College", type: "small-liberal-arts", studyAbroadUrl: "https://www.bennington.edu/global-education" },
  { school: "Ithaca College", type: "small-liberal-arts", studyAbroadUrl: "https://www.ithaca.edu/study-abroad/contact" },
  { school: "Elon University", type: "small-liberal-arts", studyAbroadUrl: "https://www.elon.edu/u/academics/global/contact/" },
  { school: "High Point University", type: "small-liberal-arts", studyAbroadUrl: "https://www.highpoint.edu/global/contact/" },
  { school: "Rollins College", type: "small-liberal-arts", studyAbroadUrl: "https://www.rollins.edu/international-programs/study-abroad/" },
  { school: "University of Puget Sound", type: "small-liberal-arts", studyAbroadUrl: "https://www.pugetsound.edu/academics/academic-resources/study-abroad/contact" },
  { school: "Willamette University", type: "small-liberal-arts", studyAbroadUrl: "https://willamette.edu/offices/international/study-abroad/" },
  { school: "St. Olaf College", type: "small-liberal-arts", studyAbroadUrl: "https://wp.stolaf.edu/international-and-off-campus-studies/contact/" },
  { school: "Luther College", type: "small-liberal-arts", studyAbroadUrl: "https://www.luther.edu/offcampus/contact/" },
  { school: "Gustavus Adolphus College", type: "small-liberal-arts", studyAbroadUrl: "https://gustavus.edu/international/study_abroad/contact.php" },
  { school: "Hope College", type: "small-liberal-arts", studyAbroadUrl: "https://hope.edu/academics/off-campus-programs/contact.html" },
  { school: "Calvin University", type: "small-liberal-arts", studyAbroadUrl: "https://calvin.edu/go-abroad/contact/" },
  { school: "Kalamazoo College", type: "small-liberal-arts", studyAbroadUrl: "https://www.kzoo.edu/cgce/contact/" },
  { school: "Beloit College", type: "small-liberal-arts", studyAbroadUrl: "https://www.beloit.edu/academics/international/contact/" },
  { school: "Knox College", type: "small-liberal-arts", studyAbroadUrl: "https://www.knox.edu/academics/off-campus-programs/contact" },
  { school: "Illinois Wesleyan University", type: "small-liberal-arts", studyAbroadUrl: "https://www.iwu.edu/global-studies/study-abroad/" },
  { school: "Lake Forest College", type: "small-liberal-arts", studyAbroadUrl: "https://www.lakeforest.edu/academics/international/study-abroad/" },
  { school: "Ripon College", type: "small-liberal-arts", studyAbroadUrl: "https://www.ripon.edu/academics/study-abroad/" },

  // ── HBCUs ─────────────────────────────────────────────────────────────
  { school: "Howard University", type: "hbcu", studyAbroadUrl: "https://www.howard.edu/provost/ugstudies/abroad.htm" },
  { school: "Spelman College", type: "hbcu", studyAbroadUrl: "https://www.spelman.edu/academics/global-learning/study-abroad" },
  { school: "Morehouse College", type: "hbcu", studyAbroadUrl: "https://www.morehouse.edu/academics/global-programs/study-abroad/" },
  { school: "Hampton University", type: "hbcu", studyAbroadUrl: "https://hamptonu.edu/academics/overseas_study/" },
  { school: "Fisk University", type: "hbcu", studyAbroadUrl: "https://www.fisk.edu/international/" },
  { school: "Xavier University of Louisiana", type: "hbcu", studyAbroadUrl: "https://www.xula.edu/international-programs/" },
  { school: "Tuskegee University", type: "hbcu", studyAbroadUrl: "https://www.tuskegee.edu/academics/colleges/cbse/international" },
  { school: "Clark Atlanta University", type: "hbcu", studyAbroadUrl: "https://www.cau.edu/academics/study-abroad.html" },
  { school: "Dillard University", type: "hbcu", studyAbroadUrl: "https://www.dillard.edu/academics/global/" },
  { school: "Bennett College", type: "hbcu", studyAbroadUrl: "https://www.bennett.edu/academics/international/" },
  { school: "Bethune-Cookman University", type: "hbcu", studyAbroadUrl: "https://www.cookman.edu/academics/international/" },
  { school: "North Carolina A&T State University", type: "hbcu", studyAbroadUrl: "https://www.ncat.edu/about/offices/research/international/" },
  { school: "Prairie View A&M University", type: "hbcu", studyAbroadUrl: "https://www.pvamu.edu/global/study-abroad/" },
  { school: "Tennessee State University", type: "hbcu", studyAbroadUrl: "https://www.tnstate.edu/global_education/" },
  { school: "Morgan State University", type: "hbcu", studyAbroadUrl: "https://www.morgan.edu/international_program.html" },
  { school: "Grambling State University", type: "hbcu", studyAbroadUrl: "https://www.gram.edu/academics/divisions/education/international/" },
  { school: "Alcorn State University", type: "hbcu", studyAbroadUrl: "https://www.alcorn.edu/academics/international/" },
  { school: "Lincoln University PA", type: "hbcu", studyAbroadUrl: "https://www.lincoln.edu/academics/international/index.html" },
  { school: "Bowie State University", type: "hbcu", studyAbroadUrl: "https://www.bowiestate.edu/academics-research/academic-outreach/international-programs/" },

  // ── Technical / Engineering Schools ───────────────────────────────────
  { school: "Massachusetts Institute of Technology", type: "tech", studyAbroadUrl: "https://studyabroad.mit.edu/contact" },
  { school: "California Institute of Technology", type: "tech", studyAbroadUrl: "https://registrar.caltech.edu/academic-information/graduate-students/international-study-opportunities" },
  { school: "Carnegie Mellon University", type: "tech", studyAbroadUrl: "https://www.cmu.edu/career/students-and-alumni/study-abroad/" },
  { school: "Georgia Institute of Technology", type: "tech", studyAbroadUrl: "https://www.oie.gatech.edu/contact" },
  { school: "Rochester Institute of Technology", type: "tech", studyAbroadUrl: "https://www.rit.edu/studying-abroad/contact" },
  { school: "Rensselaer Polytechnic Institute", type: "tech", studyAbroadUrl: "https://global.rpi.edu/studyabroad/contact" },
  { school: "Worcester Polytechnic Institute", type: "tech", studyAbroadUrl: "https://www.wpi.edu/academics/global-programs/contact" },
  { school: "Stevens Institute of Technology", type: "tech", studyAbroadUrl: "https://www.stevens.edu/academics/global-school/study-abroad/contact" },
  { school: "Illinois Institute of Technology", type: "tech", studyAbroadUrl: "https://www.iit.edu/international-center/study-abroad" },
  { school: "Lehigh University", type: "tech", studyAbroadUrl: "https://www.lehigh.edu/~inoff/contact.html" },
  { school: "Harvey Mudd College", type: "tech", studyAbroadUrl: "https://www.hmc.edu/academic-affairs/study-abroad/" },
  { school: "Rose-Hulman Institute of Technology", type: "tech", studyAbroadUrl: "https://www.rose-hulman.edu/academics/academic-opportunities/study-abroad.html" },
  { school: "Colorado School of Mines", type: "tech", studyAbroadUrl: "https://www.mines.edu/international-programs/study-abroad/" },

  // ── Regional Comprehensives (diverse, high study-abroad volume) ────────
  { school: "James Madison University", type: "regional", studyAbroadUrl: "https://www.jmu.edu/international/studyabroad/contact.shtml" },
  { school: "Appalachian State University", type: "regional", studyAbroadUrl: "https://international.appstate.edu/study-abroad/contact" },
  { school: "Western Washington University", type: "regional", studyAbroadUrl: "https://www.wwu.edu/studyabroad/contact.shtml" },
  { school: "Central Michigan University", type: "regional", studyAbroadUrl: "https://www.cmich.edu/offices-departments/education-abroad" },
  { school: "Eastern Michigan University", type: "regional", studyAbroadUrl: "https://www.emich.edu/international/study-abroad/contact.php" },
  { school: "Bowling Green State University", type: "regional", studyAbroadUrl: "https://www.bgsu.edu/international-programs-and-partnerships/contact.html" },
  { school: "Ohio University", type: "regional", studyAbroadUrl: "https://www.ohio.edu/cas/study-abroad/contact" },
  { school: "Miami University Ohio", type: "regional", studyAbroadUrl: "https://miamioh.edu/global-initiatives/study-abroad/contact/" },
  { school: "Western Michigan University", type: "regional", studyAbroadUrl: "https://wmich.edu/international/studyabroad/contact" },
  { school: "Grand Valley State University", type: "regional", studyAbroadUrl: "https://www.gvsu.edu/studyabroad/contact-us-6.htm" },
  { school: "Ball State University", type: "regional", studyAbroadUrl: "https://www.bsu.edu/academics/centersandinstitutes/burrishonors/study-abroad" },
  { school: "Illinois State University", type: "regional", studyAbroadUrl: "https://studyabroad.illinoisstate.edu/contact/" },
  { school: "Northern Illinois University", type: "regional", studyAbroadUrl: "https://niu.edu/international/students/study-abroad/index.shtml" },
  { school: "Southern Illinois University Carbondale", type: "regional", studyAbroadUrl: "https://studyabroad.siu.edu/contact.php" },
  { school: "University of North Dakota", type: "regional", studyAbroadUrl: "https://und.edu/academics/global/study-abroad.html" },
  { school: "South Dakota State University", type: "regional", studyAbroadUrl: "https://www.sdstate.edu/international-affairs/study-abroad" },
  { school: "University of South Dakota", type: "regional", studyAbroadUrl: "https://www.usd.edu/study-abroad" },
  { school: "Minnesota State Mankato", type: "regional", studyAbroadUrl: "https://mankato.mnsu.edu/university-life/campus-services/global-education/" },
  { school: "Sam Houston State University", type: "regional", studyAbroadUrl: "https://www.shsu.edu/dept/international/study-abroad/" },
  { school: "Texas State University", type: "regional", studyAbroadUrl: "https://www.international.txst.edu/study-abroad.html" },
  { school: "University of North Texas", type: "regional", studyAbroadUrl: "https://international.unt.edu/study-abroad" },
  { school: "University of Texas San Antonio", type: "regional", studyAbroadUrl: "https://www.utsa.edu/global/studyabroad/" },
  { school: "Utah State University", type: "regional", studyAbroadUrl: "https://www.usu.edu/studyabroad/contact" },
  { school: "Boise State University", type: "regional", studyAbroadUrl: "https://studyabroad.boisestate.edu/contact" },
  { school: "Idaho State University", type: "regional", studyAbroadUrl: "https://www.isu.edu/studyabroad/contact/" },
  { school: "Eastern Washington University", type: "regional", studyAbroadUrl: "https://www.ewu.edu/studyabroad" },
  { school: "Central Washington University", type: "regional", studyAbroadUrl: "https://www.cwu.edu/studyabroad/contact.html" },
  { school: "Portland State University", type: "regional", studyAbroadUrl: "https://www.pdx.edu/international/study-abroad-contact" },
  { school: "San Diego State University", type: "regional", studyAbroadUrl: "https://studyabroad.sdsu.edu/contact" },
  { school: "Cal Poly San Luis Obispo", type: "regional", studyAbroadUrl: "https://international.calpoly.edu/content/study-abroad-contact" },
  { school: "Cal State Long Beach", type: "regional", studyAbroadUrl: "https://www.csulb.edu/international-education/study-abroad/contact" },
  { school: "Cal State Fullerton", type: "regional", studyAbroadUrl: "https://international.fullerton.edu/isss/studyabroad.aspx" },
  { school: "Cal State Northridge", type: "regional", studyAbroadUrl: "https://www.csun.edu/international-programs/study-abroad/contact" },
  { school: "Cal State Sacramento", type: "regional", studyAbroadUrl: "https://www.csus.edu/college/social-sciences-interdisciplinary-studies/global-education/study-abroad/" },
  { school: "Cal State San Jose", type: "regional", studyAbroadUrl: "https://www.sjsu.edu/studyabroad/contact/" },
  { school: "Cal State Fresno", type: "regional", studyAbroadUrl: "https://www.fresnostate.edu/academics/international/studyabroad/" },
  { school: "University of Nevada Reno", type: "regional", studyAbroadUrl: "https://www.unr.edu/studyabroad/contact" },
  { school: "Montana State University", type: "regional", studyAbroadUrl: "https://www.montana.edu/studyabroad/contact.html" },
  { school: "University of Montana", type: "regional", studyAbroadUrl: "https://www.umt.edu/studyabroad/contact.php" },
  { school: "University of Wyoming", type: "regional", studyAbroadUrl: "https://www.uwyo.edu/international/study-abroad/contact-us/" },
  { school: "University of Northern Iowa", type: "regional", studyAbroadUrl: "https://studyabroad.uni.edu/contact" },
  { school: "Western Kentucky University", type: "regional", studyAbroadUrl: "https://www.wku.edu/studyabroad/contact.php" },
  { school: "Eastern Kentucky University", type: "regional", studyAbroadUrl: "https://international.eku.edu/study-abroad/contact" },
  { school: "University of Louisville", type: "regional", studyAbroadUrl: "https://louisville.edu/globaled/studyabroad/contact" },
  { school: "Marshall University", type: "regional", studyAbroadUrl: "https://www.marshall.edu/global/studyabroad/" },
  { school: "West Virginia University", type: "regional", studyAbroadUrl: "https://studyabroad.wvu.edu/contact" },
  { school: "Radford University", type: "regional", studyAbroadUrl: "https://www.radford.edu/content/global/home/study-abroad/contact.html" },
  { school: "James Madison University Harrisonburg", type: "regional", studyAbroadUrl: "https://www.jmu.edu/international/studyabroad/" },
  { school: "Towson University", type: "regional", studyAbroadUrl: "https://www.towson.edu/internationalprograms/abroad/contact.html" },
  { school: "University of Baltimore", type: "regional", studyAbroadUrl: "https://www.ubalt.edu/international-education/" },
  { school: "Salisbury University", type: "regional", studyAbroadUrl: "https://www.salisbury.edu/administration/study-abroad/contact.aspx" },
  { school: "SUNY Buffalo", type: "regional", studyAbroadUrl: "https://www.buffalo.edu/studyabroad/contact.html" },
  { school: "SUNY Stony Brook", type: "regional", studyAbroadUrl: "https://www.stonybrook.edu/studyabroad/contact/" },
  { school: "SUNY Albany", type: "regional", studyAbroadUrl: "https://www.albany.edu/studyabroad/contact.php" },
  { school: "SUNY Binghamton", type: "regional", studyAbroadUrl: "https://www.binghamton.edu/international/study-abroad/contact.html" },
  { school: "SUNY Geneseo", type: "regional", studyAbroadUrl: "https://www.geneseo.edu/study_abroad/contact" },
  { school: "SUNY New Paltz", type: "regional", studyAbroadUrl: "https://www.newpaltz.edu/studyabroad/contact.html" },
  { school: "Pace University", type: "regional", studyAbroadUrl: "https://www.pace.edu/study-abroad/contact" },
  { school: "Long Island University", type: "regional", studyAbroadUrl: "https://liu.edu/international/study-abroad" },
  { school: "Sacred Heart University", type: "regional", studyAbroadUrl: "https://www.sacredheart.edu/offices-departments/global-affairs/study-abroad/" },
  { school: "Fairfield University", type: "regional", studyAbroadUrl: "https://www.fairfield.edu/academics/academic-offices-and-resources/global-and-international-studies/study-abroad/" },
  { school: "Quinnipiac University", type: "regional", studyAbroadUrl: "https://www.qu.edu/student-life/global-engagement/study-abroad/" },
  { school: "Seton Hall University", type: "regional", studyAbroadUrl: "https://www.shu.edu/global-education/contact.cfm" },
  { school: "Rider University", type: "regional", studyAbroadUrl: "https://www.rider.edu/academics/college-arts-sciences/international-programs" },
  { school: "Rowan University", type: "regional", studyAbroadUrl: "https://global.rowan.edu/studyabroad/contact.html" },
  { school: "Monmouth University", type: "regional", studyAbroadUrl: "https://www.monmouth.edu/school-of-humanities-social-sciences/office-international-programs/" },
  { school: "Gonzaga University", type: "regional", studyAbroadUrl: "https://www.gonzaga.edu/academics/academic-resources/center-global-engagement/education-abroad" },
  { school: "Pacific Lutheran University", type: "regional", studyAbroadUrl: "https://www.plu.edu/wang-center/study-away/contact/" },
  { school: "Seattle Pacific University", type: "regional", studyAbroadUrl: "https://spu.edu/academics/global-education/study-abroad/contact" },
  { school: "Seattle University", type: "regional", studyAbroadUrl: "https://www.seattleu.edu/academics/global/study-abroad/contact/" },
  { school: "University of Portland", type: "regional", studyAbroadUrl: "https://www.up.edu/academics/study-abroad/" },
  { school: "Linfield University", type: "regional", studyAbroadUrl: "https://www.linfield.edu/international/contact.html" },
  { school: "Pacific University Oregon", type: "regional", studyAbroadUrl: "https://www.pacificu.edu/academics/international-programs/study-abroad" },
];
